stages:
  prepare:
    cmd: python faction-picker-bot\make_data.py --params params.yaml
    outs:
      - data\faction-picker-bot\featdata.csv
      - data\faction-picker-bot\vpdata.csv
    deps:
      - faction-picker-bot\creatingVPdata.ipynb
    params:
      - prepare
  prepare-step2:
    cmd: python faction-picker-bot\create_individual_datasets.py --params params.yaml
    outs:
      - data\faction-picker-bot\each-faction-data.pkl
    deps:
      - faction-picker-bot\create_individual_datasets.py
    params:
      - prepare
      - prepare-step2
  train:
    cmd: python faction-picker-bot\train_models.py --params params.yaml
    outs:
      - data\faction-picker-bot\models\
    deps:
      - faction-picker-bot\train_models.py
    params:
      - training
  create-metrics:
    cmd: python faction-picker-bot\create_metrics.py --params params.yaml
    outs:
      - data\faction-picker-bot\metrics\
    deps:
      - faction-picker-bot\create_metrics.py
    metrics:
      - data\faction-picker-bot\model_metrics.json
  #  get-shap-values:
  #    cmd: python faction-picker-bot\shap_metrics.py --params params.yaml
  #    outs:
  #      - data\faction-picker-bot\shap-metrics\
  #    deps:
  #      - data\faction-picker-bot\shap_metrics.py




