stages:
  prepare:
    cmd: papermill faction-picker-bot\creatingVPdata.ipynb -
    outs:
      - data\faction-picker-bot\featdata.csv
      - data\faction-picker-bot\vpdata.csv
    deps:
      - faction-picker-bot\creatingVPdata.ipynb
