prepare:
  folderlocation: 'terra-mystica/'
  vp-data-dir: 'data/faction-picker-bot/vpdata.csv'
  feature-data-dir: 'data/faction-picker-bot/featdata.csv'
  player-drop-dir: 'data/faction-picker-bot/unfinishedgames.csv'
prepare-step2:
  pickle-dir: 'data/faction-picker-bot/each-faction-data.pkl'
training:
  model-dir: 'data/faction-picker-bot/models/'
  num-rounds: 2000
  num-leaves: 300
  train-proportion: 0.8
  val-proportion: 0.1
  test-proportion: 0.1
create-metrics:
  metrics-dir: 'data/faction-picker-bot/metrics/'
  metrics-dir2: 'data/faction-picker-bot/model_metrics.json'
shap-metrics:
  shap-dir: 'data/faction-picker-bot/shap-metrics/'
