prepare:
  folderlocation: 'terra-mystica/'
  vp-data-dir: 'data/faction-picker-bot/vpdata.csv'
  feature-data-dir: 'data/faction-picker-bot/featdata.csv'
  player-drop-dir: 'data/faction-picker-bot/unfinishedgames.csv'
prepare-step2:
  round-features: 'one-hot'  # choose between: ['one-hot', 'ordinal']
  map-features: 'one-hot'  # choose between: ['one-hot', 'ordinal']
  playercount-features: 'ordinal'  # choose between: ['one-hot', 'ordinal']
  pickle-dir: 'data/faction-picker-bot/each-faction-data.pkl'
training:
  model-dir: 'data/faction-picker-bot/models/'
  model-metrics-dir: 'data/faction-picker-bot/model-metrics/'
  num-rounds: 3000
  num-leaves: 7
  max-depth: 7
  boosting-type: 'dart'
  train-proportion: 0.8
  val-proportion: 0.1
  test-proportion: 0.1
create-metrics:
  metrics-dir: 'data/faction-picker-bot/metrics/'
  metrics-dir2: 'data/faction-picker-bot/model_metrics.json'
  metrics-dir3: 'data/faction-picker-bot/model_plot_data.csv'
shap-metrics:
  shap-dir: 'data/faction-picker-bot/shap-metrics/'
