prepare:
  folderlocation: 'terra-mystica/'
  vp-data-dir: 'data/faction-picker-bot/vpdata.csv'
  feature-data-dir: 'data/faction-picker-bot/featdata.csv'
  player-drop-dir: 'data/faction-picker-bot/unfinishedgames.csv'
prepare-step2:
  round-features: 'one-hot'  # choose between: ['one-hot', 'ordinal']
  map-features: 'one-hot'  # choose between: ['one-hot', 'ordinal']
  playercount-features: 'ordinal'  # choose between: ['one-hot', 'ordinal']
  pickle-dir: 'data/faction-picker-bot/each-faction-data.pkl'
training:
  model-dir: 'data/faction-picker-bot/models/'
  model-metrics-dir: 'data/faction-picker-bot/model-metrics/'
  training-routine: 'lgb_train_method'  # either lgb_train_method or lgb_kfolds_scikitlearn
  train-proportion: 0.8
  val-proportion: 0.1
  test-proportion: 0.1
  split-rounds: 1500  # used only when lgb_kfolds_scikitlearn is selected
  num-rounds: 10000
  model-kwargs:
    num_leaves: 50
    learning_rate: 0.005
    max_depth: 20
    boosting_type: 'dart'
    objective: 'regression'
    feature_fraction: 0.7
create-metrics:
  metrics-dir: 'data/faction-picker-bot/metrics/'
  metrics-dir2: 'data/faction-picker-bot/model_metrics.json'
  metrics-dir3: 'data/faction-picker-bot/model_plot_data.csv'
shap-metrics:
  shap-dir: 'data/faction-picker-bot/shap-metrics/'
