prepare:
  folderlocation: 'D:/PycharmProjects/TerraBot/terra-mystica'
  vp-data-dir: 'D://PycharmProjects/TerraBot/data/faction-picker-bot/vpdata.csv'
  feature-data-dir: 'D://PycharmProjects/TerraBot/data/faction-picker-bot/featdata.csv'
  player-drop-dir: 'D://PycharmProjects/TerraBot/data/faction-picker-bot/unfinishedgames.csv'
prepare-step2:
  pickle-dir: 'D://PycharmProjects/TerraBot/data/faction-picker-bot/each-faction-data.pkl'